development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: Bob
  password: test

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: Bob
  password: test


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
