development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: Bob
  password: test

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: Bob
  password: test


production:
  adapter: postgresql
  encoding: unicode
  database: voicey_production
  pool: 5
  username: Bob
  password: test